--TAO CAC BANG DU LIEU
---TAO BANG NHAN VIEN-----
CREATE TABLE NHANVIEN (
    MaNhanVien varchar2(30) NOT NULL,
    HoTen varchar2(30) NOT NULL,
    SDT varchar2(15) UNIQUE,
    DiaChi varchar2(80) NOT NULL,
    Email varchar2(50) UNIQUE,
    DOB date NOT NULL,
    LuongCoBan INT NOT NULL,
    PhuCap int NOT NULL,
    USERNAME varchar2(20) NOT NULL,
    MaBoPhan varchar2(10) NOT NULL,
    ChiNhanh varchar2 (20),
	
	CONSTRAINT PK_NHANVIEN 
    PRIMARY KEY (MaNhanVien)
);
/

---TAO BANG BO PHAN------
CREATE TABLE BOPHAN
(
    MaBoPhan varchar2(10) NOT NULL,
    TenBoPhan varchar2(50) NOT NULL,
	
	CONSTRAINT PK_BOPHAN 
	PRIMARY KEY (MaBoPhan)
);
/

-----TAO BANG LICH TRUC PHONG----------
CREATE TABLE LICHTRUCPHONG
(
    MaPhongKham varchar2(10) NOT NULL,
    MaNhanVien varchar2(30) NOT NULL,
    ThoiGianTruc date NOT NULL,
	
	CONSTRAINT PK_LICHTRUCPHONG
	PRIMARY KEY(MaPhongKham, MaNhanVien)
);
/

----TAO BANG PHONGKHAM-----------
CREATE TABLE PHONGKHAM
(
    MaPhongKham varchar2(10) NOT NULL,
    TenPhongKham varchar2(50) NOT NULL,
	
	CONSTRAINT PK_PHONGKHAM
	PRIMARY KEY(MaPhongKham)
);
/

---TAO BANG PHIEUCHAMCONG------
CREATE TABLE PHIEUCHAMCONG
(
    MaNhanVien varchar2(20) NOT NULL,
    ThoiGianChamCong DATE NOT NULL,
    SoNgayCong int NOT NULL,
    TienLuong int NOT NULL,
	
	CONSTRAINT PK_PHIEUCHAMCONG
	PRIMARY KEY(MaNhanVien, ThoiGianChamCong)
);
/

----TAO BANG HOA DON---------
CREATE TABLE HOADON
(
    MaHoaDon varchar2(20) NOT NULL,
    NgayLapHoaDon date NOT NULL,
    TongTien int NOT NULL,
    MaKhamBenh varchar2(20) NOT NULL,
    MaNhanVien varchar2(20) NOT NULL,
    
    CONSTRAINT PK_HOADON 
	PRIMARY KEY (MaHoaDon)
);
/

---TAO BANG CHITIETHOADON----
CREATE TABLE CHITIETHOADON
(
    MaHoaDon varchar2(20) NOT NULL,
    MaDichVu varchar2(20) NOT NULL,
    
    CONSTRAINT PK_CHITIETHOADON 
	PRIMARY KEY (MaHoaDon, MaDichVu)
);
/

---TAO BANG PHIEUKHAMBENH
CREATE TABLE PHIEUKHAMBENH
(
    MaKhamBenh varchar2(20) NOT NULL,
    NgayKham date NOT NULL,
    TrieuChung varchar2(2048) NOT NULL,
    KetLuanCuaBacSi varchar2(2048) NOT NULL,
    MaBenhNhan varchar2(20) NOT NULL,
    MaNhanVien varchar2(20) NOT NULL,
    
    CONSTRAINT PK_PHIEUKHAMBENH 
	PRIMARY KEY (MaKhamBenh)
);
/

---TAO BANG BENH NHAN------
CREATE TABLE BENHNHAN
(
    MaBenhNhan varchar2(20) NOT NULL,
    HoTenBenhNhan varchar2(30) NOT NULL,
    NamSinh int NOT NULL,
    DiaChi varchar2(50) NOT NULL,
    SDT varchar2(10) NOT NULL,
    
    CONSTRAINT PK_BENHNHAN 
	PRIMARY KEY (MaBenhNhan)
);
/

---TAO BANG DICH VU----
CREATE TABLE DICHVU
(
    MaDichVu varchar2(20) NOT NULL,
    TenDichVu varchar2(20) NOT NULL,
    GiaTien int NOT NULL,
    
    CONSTRAINT PK_DICHVU 
	PRIMARY KEY (MaDichVu)
);
/

---TAO BANG PHIEUYEUCAUDICHVU-------
CREATE TABLE PHIEUYEUCAUDICHVU
(
    MaKhamBenh varchar2(20)NOT NULL,
    MaDichVu varchar2(20) NOT NULL,
    KetQuaDichVu varchar2(100) NOT NULL,
    MaNhanVien varchar2(20) NOT NULL,
    
    CONSTRAINT PK_PHIEUYEUCAUDICHVU 
	PRIMARY KEY (MaKhamBenh, MaDichVu)
);
/

---TAO BANG TOATHUOC----
CREATE TABLE TOATHUOC
(
    MaDonThuoc varchar2(20) NOT NULL,
    NgayLapDon date NOT NULL,
    TongTien int NOT NULL,
    MaKhamBenh varchar2(20) NOT NULL,
    
    
    CONSTRAINT PK_TOATHUOC 
	PRIMARY KEY (MaDonThuoc)
);
/

---TAO BANG CHITIETTOATHUOC---
CREATE TABLE CHITIETTOATHUOC
(
    MaThuoc varchar2(20) NOT NULL,
    MaDonThuoc varchar2(20) NOT NULL,
    SoLuong int NOT NULL,
    LieuLuong varchar2(50) NOT NULL,
    
    
    CONSTRAINT PK_CHITIETTOATHUOC 
	PRIMARY KEY (MaThuoc, MaDonThuoc)
);
/

---TAO BANG THUOC----
CREATE TABLE THUOC
(
    MaThuoc varchar2(20) NOT NULL,
    TenThuoc varchar2(50) NOT NULL,
    DonGia int NOT NULL,
    DonViTinh varchar2(10) NOT NULL,
    LuuY varchar2(50) NOT NULL,
    
    CONSTRAINT PK_THUOC 
	PRIMARY KEY (MaThuoc)
);
/

--TAO BANG QUANLY
CREATE TABLE QUANLY 
(
    USERNAME VARCHAR2(50),
    USER_ROLE VARCHAR2 (50),
    
    CONSTRAINT PK_QL
    PRIMARY KEY (USERNAME)
);

----TAO KHOA NGOAI NHANVIEN-BOPHAN-----------
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_BOPHAN
    FOREIGN KEY (MaBoPhan)
    REFERENCES BOPHAN(MaBoPhan);
/

----TAO KHOA NGOAI LICHTRUCPHONG-NHANVIEN
ALTER TABLE LICHTRUCPHONG
ADD CONSTRAINT FK_LICHTRUCPHONG_NHANVIEN
FOREIGN KEY (MaNhanVien)
REFERENCES NHANVIEN(MaNhanVien);
/

----TAO KHOA NGOAI LICHTRUCPHONG-PHONGKHAM----
ALTER TABLE LICHTRUCPHONG
ADD CONSTRAINT FK_LICHTRUCPHONG_PHONGKHAM
FOREIGN KEY (MaPhongKham)
REFERENCES PHONGKHAM(MaPhongKham);
/

---TAO KHOA NGOAI PHIEUCHAMCONG-NHANVIEN----
ALTER TABLE PHIEUCHAMCONG
ADD CONSTRAINT FK_PHIEUCHAMCONG_NHANVIEN_
FOREIGN KEY (MaNhanVien)
REFERENCES NHANVIEN(MaNhanVien);
/

----TAO KHOA NGOAI HOADON-NHANVIEN-----
ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_NHANVIEN_
FOREIGN KEY (MaNhanVien)
REFERENCES NHANVIEN(MaNhanVien);
/

----TAO KHOA NGOAI HOADON-PHIEUKHAMBENH------
ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_PHIEUKHAMBENH
FOREIGN KEY (MaKhamBenh)
REFERENCES PHIEUKHAMBENH(MaKhamBenh);
/

---TAO KHOA NGOAI CHITIETHOADON-HOADON----
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_HOADON
FOREIGN KEY (MaHoaDon)
REFERENCES HOADON(MaHoaDon);
/

---TAO KHOA NGOAI CHITIETHOADON-DICHVU----
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_DICHVU
FOREIGN KEY (MaDichVu)
REFERENCES DichVu;
/

---TAO KHOA NGOAI PHIEUKHAMBENH-NHANVIEN----
ALTER TABLE PHIEUKHAMBENH
ADD CONSTRAINT FK_PHIEUKHAMBENH_NHANVIEN
FOREIGN KEY (MaNhanVien)
REFERENCES NhanVien(MaNhanVien);
/

---TAO KHOA NGOAI PHIEUKHAMBENH-BENHNHAN-----
ALTER TABLE PHIEUKHAMBENH
ADD CONSTRAINT FK_PHIEUKHAMBENH_BENHNHAN
FOREIGN KEY (MaBenhNhan)
REFERENCES BENHNHAN(MaBenhNhan);
/

---TAO KHOA NGOAI PHIEUYEUCAUDICHVU-PHIEUKHAMBENH----
ALTER TABLE PHIEUYEUCAUDICHVU
ADD CONSTRAINT FK_PHIEUYEUCAUDICHVU_PHIEUKHAMBENH
FOREIGN KEY (MaKhamBenh)
REFERENCES PHIEUKHAMBENH(MaKhamBenh);
/

---TAO KHOA NGOAI PHIEUYEUCAUDICHVU-NHANVIEN---
ALTER TABLE PHIEUYEUCAUDICHVU
ADD CONSTRAINT FK_PHIEUYEUCAUDICHVU_NHANVIEN
FOREIGN KEY (MaNhanVien)
REFERENCES NHANVIEN(MaNhanVien);
/

---TAO KHOA NGOAI PHIEUYEUCAUDICHVU-DICHVU----
ALTER TABLE PHIEUYEUCAUDICHVU
ADD CONSTRAINT FK_PHIEUYEUCAUDICHVU_DICHVU
FOREIGN KEY (MaDichVu)
REFERENCES DICHVU(MaDichVu);
/

---TAO KHOA NGOAI TOATHUOC-PHIEUKHAMBENH----
ALTER TABLE TOATHUOC
ADD CONSTRAINT FK_TOATHUOC_PHIEUKHAMBENH
FOREIGN KEY (MaKhamBenh)
REFERENCES PHIEUKHAMBENH(MaKhamBenh);
/

---TAO KHOA NGOAI CHITIETTOATHUOC-TOATHUOC---
ALTER TABLE CHITIETTOATHUOC
ADD CONSTRAINT FK_CHITIETTOATHUOC_TOATHUOC
FOREIGN KEY (MaDonThuoc)
REFERENCES TOATHUOC(MaDonThuoc);
/

---TAO KHOA NGOAI CHITIETTOATHUOC-THUOC----
ALTER TABLE CHITIETTOATHUOC
ADD CONSTRAINT FK_CHITIETTOATHUOC_THUOC
FOREIGN KEY (MaThuoc)
REFERENCES THUOC(MaThuoc);
/

--TAO CAC RANG BUOC TOAN VEN
CREATE OR REPLACE TRIGGER NHANVIEN_LUONG
BEFORE INSERT OR UPDATE OF LuongCoBan
ON NHANVIEN
FOR EACH ROW
WHEN (new.LuongCoBan <= 0)
DECLARE
    positive_value EXCEPTION;
BEGIN
    RAISE positive_value;
    
    Exception
    WHEN positive_value then
        DBMS_OUTPUT.PUT_LINE('Luong phai la so nguyen duong');
END;
/

CREATE OR REPLACE TRIGGER NHANVIEN_DOB
BEFORE INSERT OR UPDATE OF DOB
ON NHANVIEN
FOR EACH ROW
BEGIN  
        IF (EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM :new.DOB) < 18) THEN
            dbms_output.put_line ('Nhan vien phai tren 18 tuoi');
        END IF;
END;
/

CREATE OR REPLACE TRIGGER NHANVIEN_PHUCAP
BEFORE INSERT OR UPDATE OF LuongCoBan
ON NHANVIEN
FOR EACH ROW
WHEN (new.LuongCoBan <= 0)
DECLARE
    positive_value EXCEPTION;
BEGIN
    RAISE positive_value;
    
    Exception
    WHEN positive_value then
        DBMS_OUTPUT.PUT_LINE('Phu cap phai la so nguyen duong');
END;
/

CREATE OR REPLACE TRIGGER CHAMCONG_SONGAYCONG
BEFORE INSERT OR UPDATE OF SONGAYCONG
ON PHIEUCHAMCONG
FOR EACH ROW
DECLARE
    D_CURRENT date;
    max_date int; 
BEGIN
    D_CURRENT:= :NEW.THOIGIANCHAMCONG; 
    max_date := EXTRACT(DAY FROM(LAST_DAY(D_CURRENT)));
    
    IF(:NEW.SONGAYCONG > MAX_DATE OR :NEW.SONGAYCONG < 0) THEN
        DBMS_OUTPUT.PUT_LINE('So ngay cong hop le');
    END IF;     
END;
/

CREATE OR REPLACE TRIGGER DICHVU_PHIDICHVU
BEFORE INSERT OR UPDATE OF GiaTien
ON DICHVU
FOR EACH ROW
WHEN (new.GIATIEN <= 0)
DECLARE
    positive_value EXCEPTION;
BEGIN
    RAISE positive_value;
    
    Exception
    WHEN positive_value then
        DBMS_OUTPUT.PUT_LINE('Gia tien phai la so nguyen duong');
END;
/

CREATE OR REPLACE TRIGGER TOATHUOC_TONGTIEN
BEFORE INSERT OR UPDATE OF TongTien
ON ToaThuoc
FOR EACH ROW
WHEN (new.TongTien <= 0)
DECLARE
    positive_value EXCEPTION;
BEGIN
    RAISE positive_value;
    
    Exception
    WHEN positive_value then
        DBMS_OUTPUT.PUT_LINE('Gia tien phai la so nguyen duong');
END;
/

CREATE OR REPLACE TRIGGER CTTOATHUOC_SLG
BEFORE INSERT OR UPDATE OF SoLuong
ON CHITIETTOATHUOC
FOR EACH ROW
WHEN (new.SOLUONG <= 0)
DECLARE
    positive_value EXCEPTION;
BEGIN
    RAISE positive_value;
    
    Exception
    WHEN positive_value then
        DBMS_OUTPUT.PUT_LINE('So luong phai la so nguyen duong');
END;
/

CREATE OR REPLACE TRIGGER THUOC_DONGIA
BEFORE INSERT OR UPDATE OF DONGIA
ON THUOC
FOR EACH ROW
WHEN (new.DONGIA <= 0)
DECLARE
    positive_value EXCEPTION;
BEGIN
    RAISE positive_value;
    
    Exception
    WHEN positive_value then
        DBMS_OUTPUT.PUT_LINE('Don gia phai la so nguyen duong');
END;
/

--proc tao view
create or replace procedure  GRANT_SELECT_ON_COLUMN
(Table_name in varchar2, user_name in varchar2, column_list in varchar2, grant_opt in char)
AS
        view_name varchar2(200);
        create_view_statement varchar2(1000);
        grant_statement varchar2(100);
        grant_opt_statement varchar2(100);
 begin       
    view_name := table_name ||'' || column_list || '' || user_name ||'_view';
    create_view_statement := 'create or replace view ' || view_name || ' as '
    || 'select ' || column_list || ' from ' || Table_name;
    EXECUTE IMMEDIATE create_view_statement;
      
    if(grant_opt = 'N')
    then
        grant_statement := 'grant select on ' || view_name ||
        ' to ' || user_name;
         EXECUTE IMMEDIATE grant_statement; 
    else
        grant_opt_statement :=
        'grant select on ' || view_name ||
        ' to ' || user_name ||
        ' with grant option';
        EXECUTE IMMEDIATE grant_opt_statement;
    end if;
END;

CREATE OR REPLACE PROCEDURE INSERT_PKB (
    I_MAKHAMBENH    PHIEUKHAMBENH.MAKHAMBENH%TYPE,
    I_NGAYKHAM      PHIEUKHAMBENH.NGAYKHAM%TYPE,
    I_TRIEUCHUNG    PHIEUKHAMBENH.TRIEUCHUNG%TYPE,
    I_KETLUANCUABS  PHIEUKHAMBENH.KETLUANCUABACSI%TYPE,
    I_MABENHNHAN    PHIEUKHAMBENH.MABENHNHAN%TYPE,
    I_MANHANVIEN    PHIEUKHAMBENH.MABENHNHAN%TYPE)
IS
BEGIN
    INSERT INTO PHIEUKHAMBENH
    VALUES
    (I_MAKHAMBENH,TO_DATE(I_NGAYKHAM, 'DD/MM/YYYY'),I_TRIEUCHUNG,I_KETLUANCUABS,I_MABENHNHAN,I_MANHANVIEN);
    
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE GRANT_ROLE 
(USERNAME VARCHAR2, GRANT_ROLE VARCHAR2, GRANT_OPTION INT) 
--GRANT OPT = 0 => KHONG THE GRANT ROLE CHO USER KHAC
--GRANT OPT - 1 => CO THE GRANT ROLE CHO USER KHAC
AS
    QUERY_STRING VARCHAR2(100);
BEGIN
    
    IF(GRANT_OPTION = 1) THEN
       QUERY_STRING := 'GRANT '||GRANT_ROLE ||' TO '||USERNAME || ' WITH GRANT OPTION';
    ELSE
        QUERY_STRING := 'GRANT '||GRANT_ROLE ||' TO '||USERNAME;
    END IF;
    
    EXECUTE IMMEDIATE query_string;
    
    INSERT INTO QUANLY
    VALUES (USERNAME, GRANT_ROLE);
    COMMIT;    
END;





