ALTER TABLE PHIEUKHAMBENH
MODIFY
    TRIEUCHUNG VARCHAR2(2048);
    
ALTER TABLE PHIEUKHAMBENH
MODIFY
    KETLUANCUABACSI VARCHAR2(2048);

CREATE OR REPLACE PROCEDURE INSERT_PKB (
    I_MAKHAMBENH    PHIEUKHAMBENH.MAKHAMBENH%TYPE,
    I_NGAYKHAM      PHIEUKHAMBENH.NGAYKHAM%TYPE,
    I_TRIEUCHUNG    PHIEUKHAMBENH.TRIEUCHUNG%TYPE,
    I_KETLUANCUABS  PHIEUKHAMBENH.KETLUANCUABACSI%TYPE,
    I_MABENHNHAN    PHIEUKHAMBENH.MABENHNHAN%TYPE,
    I_MANHANVIEN    PHIEUKHAMBENH.MABENHNHAN%TYPE)
IS
BEGIN
    INSERT INTO PHIEUKHAMBENH
    VALUES
    (I_MAKHAMBENH,TO_DATE(I_NGAYKHAM, 'DD/MM/YYYY'),I_TRIEUCHUNG,I_KETLUANCUABS,I_MABENHNHAN,I_MANHANVIEN);
    
    COMMIT;
END;
/

SELECT * FROM PHIEUKHAMBENH;