--Role nhan vien ke toan
CREATE ROLE NV_KETOAN;
GRANT CONNECT TO NV_KETOAN;

GRANT INSERT ON PHIEUCHAMCONG TO NV_KETOAN;
GRANT SELECT ON PHIEUCHAMCONG TO NV_KETOAN;
GRANT UPDATE ON PHIEUCHAMCONG TO NV_KETOAN;
GRANT SELECT ON BOPHAN TO NV_KETOAN;

CREATE VIEW LUONG_CB_PHU_CAP AS
SELECT LUONGCOBAN, PHUCAP
FROM NHANVIEN;
GRANT SELECT ON LUONG_CB_PHU_CAP TO NV_KETOAN;

--Role nhan vien tai vu
CREATE ROLE NV_TAIVU;
GRANT CONNECT TO NV_TAIVU;

GRANT SELECT ON BOPHAN TO NV_TAIVU;
GRANT SELECT ON CHITIETHOADON TO NV_TAIVU;
GRANT INSERT ON CHITIETHOADON TO NV_TAIVU;
GRANT UPDATE ON CHITIETHOADON TO NV_TAIVU;
GRANT SELECT ON HOADON TO NV_TAIVU;
GRANT INSERT ON HOADON TO NV_TAIVU;
GRANT UPDATE ON HOADON TO NV_TAIVU;
GRANT SELECT ON DICHVU TO NV_TAIVU;

CREATE VIEW PYC_DV_NV_TV AS
SELECT MAKHAMBENH, MADICHVU, MANHANVIEN
FROM PHIEUYEUCAUDICHVU;
GRANT SELECT ON PYC_DV_NV_TV TO NV_TAIVU;

--ROLE NV_QL_CHUYENMON
CREATE ROLE NV_QL_CHUYENMON;
GRANT CONNECT TO NV_QL_CHUYENMON;

GRANT SELECT ON PHONGKHAM TO NV_QL_CHUYENMON;
GRANT SELECT ON LICHTRUCPHONG TO NV_QL_CHUYENMON;
GRANT SELECT ON PHIEUCHAMCONG TO NV_QL_CHUYENMON;
GRANT SELECT ON NHANVIEN TO NV_QL_CHUYENMON;
GRANT SELECT ON BENHNHAN TO NV_QL_CHUYENMON;
GRANT SELECT ON PHIEUKHAMBENH TO NV_QL_CHUYENMON;
GRANT SELECT ON THUOC TO NV_QL_CHUYENMON;
GRANT SELECT ON CHITIETTOATHUOC TO NV_QL_CHUYENMON;
GRANT SELECT ON TOATHUOC TO NV_QL_CHUYENMON;
GRANT SELECT ON BOPHAN TO NV_QL_CHUYENMON;
GRANT SELECT ON DICHVU TO NV_QL_CHUYENMON;
GRANT SELECT ON CHITIETHOADON TO NV_QL_CHUYENMON;
GRANT SELECT ON HOADON TO NV_QL_CHUYENMON;
GRANT SELECT ON PHIEUYEUCAUDICHVU TO NV_QL_CHUYENMON;

--ROLE NV_QL_TAIVU
CREATE ROLE NV_QL_TAIVU;
GRANT CONNECT TO NV_QL_TAIVU;

GRANT SELECT ON PHONGKHAM TO NV_QL_TAIVU;
GRANT SELECT ON LICHTRUCPHONG TO NV_QL_TAIVU;
GRANT SELECT ON PHIEUCHAMCONG TO NV_QL_TAIVU;
GRANT SELECT ON NHANVIEN TO NV_QL_TAIVU;
GRANT SELECT ON BENHNHAN TO NV_QL_TAIVU;
GRANT SELECT ON PHIEUKHAMBENH TO NV_QL_TAIVU;
GRANT SELECT ON THUOC TO NV_QL_TAIVU;
GRANT INSERT (DONGIA) ON THUOC TO NV_QL_TAIVU; 
GRANT UPDATE (DONGIA) ON THUOC TO NV_QL_TAIVU;
GRANT SELECT ON CHITIETTOATHUOC TO NV_QL_TAIVU;
GRANT SELECT ON TOATHUOC TO NV_QL_TAIVU;
GRANT SELECT ON BOPHAN TO NV_QL_TAIVU;
GRANT SELECT ON DICHVU TO NV_QL_TAIVU;
GRANT INSERT (GIATIEN) ON DICHVU TO NV_QL_TAIVU; 
GRANT UPDATE (GIATIEN) ON DICHVU TO NV_QL_TAIVU;
GRANT SELECT ON CHITIETHOADON TO NV_QL_TAIVU;
GRANT SELECT ON HOADON TO NV_QL_TAIVU;
GRANT SELECT ON PHIEUYEUCAUDICHVU TO NV_QL_TAIVU;

--ROLE QUAN LY TAI NGUYEN VA NHAN SU
CREATE ROLE NV_QL_TN_NS;
GRANT CONNECT TO NV_QL_TN_NS;

GRANT SELECT ON PHONGKHAM TO NV_QL_TN_NS;
GRANT INSERT ON PHONGKHAM TO NV_QL_TN_NS;
GRANT UPDATE ON PHONGKHAM TO NV_QL_TN_NS;
GRANT SELECT ON LICHTRUCPHONG TO NV_QL_TN_NS;
GRANT INSERT ON LICHTRUCPHONG TO NV_QL_TN_NS;
GRANT UPDATE ON LICHTRUCPHONG TO NV_QL_TN_NS;
GRANT SELECT ON PHIEUCHAMCONG TO NV_QL_TN_NS;
GRANT INSERT ON NHANVIEN TO NV_QL_TN_NS;
GRANT SELECT ON NHANVIEN TO NV_QL_TN_NS;
GRANT UPDATE ON NHANVIEN TO NV_QL_TN_NS;
GRANT DELETE ON NHANVIEN TO NV_QL_TN_NS;
GRANT SELECT ON BENHNHAN TO NV_QL_TN_NS;
GRANT INSERT ON BOPHAN TO NV_QL_TN_NS;
GRANT SELECT ON BOPHAN TO NV_QL_TN_NS;
GRANT UPDATE ON BOPHAN TO NV_QL_TN_NS;
GRANT DELETE ON BOPHAN TO NV_QL_TN_NS;

--Role Nhan vien ban thuoc
CREATE ROLE NV_BANTHUOC;
GRANT CONNECT TO NV_BANTHUOC;

GRANT SELECT ON THUOC TO NV_BANTHUOC;
GRANT SELECT ON CHITIETTOATHUOC TO NV_BANTHUOC;
GRANT SELECT ON TOATHUOC TO NV_BANTHUOC;
GRANT UPDATE (TONGTIEN) ON TOATHUOC TO NV_BANTHUOC;
GRANT SELECT ON BOPHAN TO NV_BANTHUOC;
GRANT SELECT ON PHIEUCHAMCONG TO NV_BANTHUOC;

--ROLE BACSI
CREATE ROLE BACSI;
GRANT CONNECT TO BACSI;

GRANT SELECT ON PHIEUKHAMBENH TO BACSI;
GRANT SELECT ON  PHIEUCHAMCONG TO BACSI;
GRANT SELECT ON  NHANVIEN TO BACSI;
GRANT INSERT, UPDATE, SELECT, DELETE ON TOATHUOC TO BACSI;
GRANT INSERT, UPDATE, SELECT, DELETE ON CHITIETTOATHUOC TO BACSI;
GRANT SELECT ON LICHTRUCPHONG TO BACSI;
GRANT SELECT ON PHONGKHAM TO BACSI;
GRANT SELECT ON THUOC TO BACSI;
GRANT SELECT ON BOPHAN TO BACSI;
GRANT SELECT ON DICHVU TO BACSI;
GRANT INSERT, UPDATE, SELECT, DELETE ON PHIEUYEUCAUDICHVU TO BACSI;

--Role Tiep tan va dieu phoi
CREATE ROLE TIEPTAN_DIEUPHOI;
GRANT CONNECT TO TIEPTAN_DIEUPHOI;

GRANT SELECT ON PHONGKHAM TO TIEPTAN_DIEUPHOI;
GRANT SELECT ON LICHTRUCPHONG TO TIEPTAN_DIEUPHOI;
GRANT INSERT, UPDATE, SELECT ON BENHNHAN TO TIEPTAN_DIEUPHOI;
GRANT SELECT ON BOPHAN TO TIEPTAN_DIEUPHOI;
GRANT INSERT ON PHIEUKHAMBENH TO TIEPTAN_DIEUPHOI;
GRANT INSERT ON PHIEUYEUCAUDICHVU TO TIEPTAN_DIEUPHOI;
GRANT UPDATE(NGAYKHAM, TRIEUCHUNG, MABENHNHAN, MANHANVIEN) ON PHIEUKHAMBENH TO TIEPTAN_DIEUPHOI; 


CREATE TABLE QUANLY 
(
    USERNAME VARCHAR2(50),
    USER_ROLE VARCHAR2 (50),
    
    CONSTRAINT PK_QL
    PRIMARY KEY (USERNAME)
);


 