DROP ROLE TIEPTAN_DIEUPHOI;
CREATE ROLE TIEPTAN_DIEUPHOI;
DROP ROLE BACSI;
CREATE ROLE BACSI;
DROP ROLE BANTHUOC;
CREATE ROLE BANTHUOC;

GRANT INSERT, DELETE, UPDATE, SELECT ON BENHNHAN TO TIEPTAN_DIEUPHOI;
GRANT INSERT ON PHIEUKHAMBENH TO TIEPTAN_DIEUPHOI;
GRANT UPDATE(NGAYKHAM, TRIEUCHUNG, MABENHNHAN, MANHANVIEN) ON PHIEUKHAMBENH TO TIEPTAN_DIEUPHOI; 
GRANT INSERT ON PHIEUYEUCAUDICHVU TO TIEPTAN_DIEUPHOI;

GRANT UPDATE(KETLUANCUABACSI) ON PHIEUKHAMBENH TO BACSI;
GRANT INSERT, UPDATE ON TOATHUOC TO BACSI;
GRANT INSERT, UPDATE ON CHITIETTOATHUOC TO BACSI;
GRANT SELECT ON LICHTRUCPHONG TO BACSI;
GRANT SELECT ON PHONGKHAM TO BACSI;
GRANT SELECT ON THUOC TO BACSI;


GRANT SELECT ON TOATHUOC TO BANTHUOC;
GRANT SELECT ON CHITIETTOATHUOC TO BANTHUOC;