CREATE USER BAC_SI IDENTIFIED BY 1234;
GRANT BACSI TO BAC_SI;

UPDATE  NHANVIEN
SET USERNAME = 'BAC_SI'
WHERE MANHANVIEN = 'NV011';


--TAO POLICY TREN BANG PHIEU CHAM CONG
CREATE OR REPLACE FUNCTION PCC_POLICY (p_schema varchar2, p_obj varchar2)
RETURN VARCHAR2
AS 
    --TYPE CURRENT_ROLE IS TABLE OF VARCHAR2(50);
    --CHECK_ROLE CURRENT_ROLE := CURRENT_ROLE();
    CHECK_ROLE NUMBER DEFAULT 0;
    --CHECK_DBA NUMBER DEFAULT 0;
    USER_NAME VARCHAR2 (100);
    MANV NHANVIEN.MANHANVIEN%TYPE DEFAULT NULL;
BEGIN
    USER_NAME := SYS_CONTEXT ('USERENV', 'SESSION_USER'); --Lay username
    SELECT manhanvien INTO MANV FROM nhanvien --Lay ma nv
    WHERE USERNAME = USER_NAME;
    -- 
    SELECT COUNT(*) INTO CHECK_ROLE FROM USER_ROLE_PRIVS
    WHERE GRANTED_ROLE = 'TIEPTAN_DIEUPHOI';
    
    IF (CHECK_ROLE = 1) THEN
        CHECK_ROLE := 0;
        RETURN 'MANHANVIEN = '''||MANV||'''';
    END IF;
     --   
    SELECT COUNT(*) INTO CHECK_ROLE FROM USER_ROLE_PRIVS
    WHERE GRANTED_ROLE = 'NV_TAIVU';
    
    IF (CHECK_ROLE = 1) THEN
        CHECK_ROLE := 0;
        RETURN 'MANHANVIEN = '''||MANV||'''';
    END IF;   
    --
    SELECT COUNT(*) INTO CHECK_ROLE FROM USER_ROLE_PRIVS
    WHERE GRANTED_ROLE = 'BACSI';
    
    IF (CHECK_ROLE = 1) THEN
        CHECK_ROLE := 0;
        RETURN 'MANHANVIEN = '''||MANV||'''';
    END IF;
    --
    SELECT COUNT(*) INTO CHECK_ROLE FROM USER_ROLE_PRIVS
    WHERE GRANTED_ROLE = 'NV_BANTHUOC';
    
    IF (CHECK_ROLE = 1) THEN
        CHECK_ROLE := 0;
        RETURN 'MANHANVIEN = '''||MANV||'''';
    END IF;
    
    RETURN ('1=1');
END;
/

BEGIN
    DBMS_RLS.ADD_POLICY (
    OBJECT_SCHEMA => 'DBA_QLBV',
    OBJECT_NAME => 'PHIEUCHAMCONG',
    POLICY_NAME => 'QLBV_PCC_POLICY',
    POLICY_FUNCTION => 'PCC_POLICY');
END;
/

BEGIN
    DBMS_RLS.DROP_POLICY (
    OBJECT_SCHEMA => 'DBA_QLBV',
    OBJECT_NAME => 'PHIEUCHAMCONG',
    POLICY_NAME => 'QLBV_PCC_POLICY');
END;
    
/

/*
col predicate format a50;
SELECT PCC_POLICY ('DBA_QLBV','PHIEUCHAMCONG') predicate
FROM DUAL;
*/



    
