--TAO POLICY TREN BANG PHIEU CHAM CONG
CREATE OR REPLACE FUNCTION PCC_POLICY (p_schema varchar2, p_obj varchar2)
RETURN VARCHAR2
AS 
    CHECK_ROLE QUANLY.USER_ROLE%TYPE;
    TEN VARCHAR2 (100);
    MANV NHANVIEN.MANHANVIEN%TYPE DEFAULT NULL;
BEGIN
    TEN := SYS_CONTEXT ('USERENV', 'SESSION_USER'); --Lay username
    SELECT manhanvien INTO MANV FROM nhanvien --Lay ma nv
    WHERE USERNAME = TEN;
    
    ----LAY ROLE 
    SELECT USER_ROLE INTO CHECK_ROLE 
    FROM QUANLY
    WHERE USERNAME = TEN;
    
    --
    IF(CHECK_ROLE = 'TIEPTAN_DIEUPHOI') THEN
        RETURN 'MANHANVIEN = '''||MANV||'''';
    END IF;
     --   
      IF(CHECK_ROLE = 'NV_TAIVU') THEN
        RETURN 'MANHANVIEN = '''||MANV||'''';
    END IF;
    --
     IF(CHECK_ROLE = 'BACSI') THEN
        RETURN 'MANHANVIEN = '''||MANV||'''';
    END IF;
    --
    IF(CHECK_ROLE = 'NV_BANTHUOC') THEN
        RETURN 'MANHANVIEN = '''||MANV||'''';
    END IF;
    
    RETURN '1=1';
END;
/

BEGIN
    DBMS_RLS.ADD_POLICY (
    OBJECT_SCHEMA => 'DBA_QLBV',
    OBJECT_NAME => 'PHIEUCHAMCONG',
    POLICY_NAME => 'QLBV_PCC_POLICY',
    POLICY_FUNCTION => 'PCC_POLICY',
    STATEMENT_TYPES => 'SELECT');
END;
/

--TAO POLICY TREN BANG PHIEUKHAMBENH
CREATE OR REPLACE FUNCTION PKB_POLICY (p_schema varchar2, p_obj varchar2)
RETURN VARCHAR2
AS 
    CHECK_ROLE QUANLY.USER_ROLE%TYPE;
    TEN VARCHAR2 (100);
    MANV NHANVIEN.MANHANVIEN%TYPE DEFAULT NULL;
BEGIN
    
    TEN := SYS_CONTEXT ('USERENV', 'SESSION_USER'); --Lay username
    SELECT manhanvien INTO MANV FROM nhanvien --Lay ma nv
    WHERE USERNAME = TEN;
    
    ----LAY ROLE 
    SELECT USER_ROLE INTO CHECK_ROLE 
    FROM QUANLY
    WHERE USERNAME = TEN;
    
     IF(CHECK_ROLE = 'BACSI') THEN
        RETURN 'MANHANVIEN = '''||MANV||'''';
    ELSE
        RETURN '1=1';
    END IF;        
END;
/

BEGIN
    DBMS_RLS.ADD_POLICY (
    OBJECT_SCHEMA => 'DBA_QLBV',
    OBJECT_NAME => 'PHIEUKHAMBENH',
    POLICY_NAME => 'QLBV_PKB_POLICY',
    POLICY_FUNCTION => 'PKB_POLICY',
    STATEMENT_TYPES => 'SELECT, UPDATE',
    UPDATE_CHECK => TRUE);
END;
/




    
