--TAO POLICY
BEGIN 
    SA_SYSDBA.CREATE_POLICY (
    POLICY_NAME => 'ACCESS_NHANVIEN',
    COLUMN_NAME =>'OLS_NHANVIEN');
END;
/

--TAO THANH PHAN LEVEL
BEGIN
    SA_COMPONENTS.CREATE_LEVEL (
    POLICY_NAME => 'ACCESS_NHANVIEN',
    LEVEL_NUM   => 40,
    SHORT_NAME  => 'QL',
    LONG_NAME   => 'QUAN LY');

    SA_COMPONENTS.CREATE_LEVEL (
    POLICY_NAME => 'ACCESS_NHANVIEN',
    LEVEL_NUM   => 30,
    SHORT_NAME  => 'NV',
    LONG_NAME   => 'NHANVIEN');
END;
/

--TAO THANH PHAN COMPARTNENT
BEGIN 
    SA_COMPONENTS.CREATE_COMPARTMENT (
    POLICY_NAME => 'ACCESS_NHANVIEN',
    COMP_NUM    =>  85, 
    SHORT_NAME  => 'NS',
    LONG_NAME   => 'NHANSU');

    SA_COMPONENTS.CREATE_COMPARTMENT (
    POLICY_NAME => 'ACCESS_NHANVIEN',
    COMP_NUM    => 65, 
    SHORT_NAME  => 'CM',
    LONG_NAME   => 'CHUYENMON');
END;
/

--TAO THANH PHAN GROUP
BEGIN
    SA_COMPONENTS.CREATE_GROUP (
    POLICY_NAME => 'ACCESS_NHANVIEN',
    GROUP_NUM   => 1000,
    SHORT_NAME  => 'CNA',
    LONG_NAME   => 'CHI NHANH A',
    PARENT_NAME => NULL);

    SA_COMPONENTS.CREATE_GROUP (
    POLICY_NAME => 'ACCESS_NHANVIEN',
    GROUP_NUM   => 1100,
    SHORT_NAME  => 'CNB',
    LONG_NAME   => 'CHI NHANH B',
    PARENT_NAME => NULL);
END;
/

--TAO CAC NHAN CHO USER VA DATA
BEGIN 
    SA_LABEL_ADMIN.CREATE_LABEL ( 
    POLICY_NAME => 'ACCESS_NHANVIEN',
    LABEL_TAG   => '1',
    LABEL_VALUE => 'QL'); 
    
    SA_LABEL_ADMIN.CREATE_LABEL ( 
    POLICY_NAME => 'ACCESS_NHANVIEN',
    LABEL_TAG   => '2',
    LABEL_VALUE => 'NV');
    
    SA_LABEL_ADMIN.CREATE_LABEL --DBA
    ('ACCESS_NHANVIEN', 500, 'QL:NS,CM:CNA,CNB');
    
     SA_LABEL_ADMIN.CREATE_LABEL
    ('ACCESS_NHANVIEN', 320, 'QL:NS,CM:CNA');  --QLNS CHI NHANH A
    
     SA_LABEL_ADMIN.CREATE_LABEL
    ('ACCESS_NHANVIEN', 330, 'QL:NS,CM:CNB'); --QLNS CHI NHANH B
    
     SA_LABEL_ADMIN.CREATE_LABEL
    ('ACCESS_NHANVIEN', 340, 'NV:NS:CNA');  --NVNS CHI NHANH A

       SA_LABEL_ADMIN.CREATE_LABEL
    ('ACCESS_NHANVIEN', 350, 'NV:NS:CNB');  --NVNS CHI NHANH B
    
     SA_LABEL_ADMIN.CREATE_LABEL  --Label cua GD CNA
    ('ACCESS_NHANVIEN', 360, 'QL:NS:CNA');
    
     SA_LABEL_ADMIN.CREATE_LABEL --LABEL CUA GD CNB
    ('ACCESS_NHANVIEN', 370, 'QL:NS:CNB');
    
    SA_LABEL_ADMIN.CREATE_LABEL --LABEL CUA NVCM CNA
    ('ACCESS_NHANVIEN', 290, 'NV:CM:CNA');
    
    SA_LABEL_ADMIN.CREATE_LABEL --LABEL CUA NVCM CNB
    ('ACCESS_NHANVIEN', 280, 'NV:CM:CNB');
    
    SA_LABEL_ADMIN.CREATE_LABEL --LABEL CUA QLCM CNA
    ('ACCESS_NHANVIEN', 270, 'QL:CM:CNA');
    
    SA_LABEL_ADMIN.CREATE_LABEL --LABEL CUA QLCM CNB
    ('ACCESS_NHANVIEN', 260, 'QL:CM:CNB');
END; 
/

--GAN POLICY LEN BANG NHANVIEN
BEGIN
    SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
    POLICY_NAME     => 'ACCESS_NHANVIEN', 
    SCHEMA_NAME     => 'DBA_QLBV', 
    TABLE_NAME      => 'NHANVIEN', 
    TABLE_OPTIONS   => 'READ_CONTROL');
END;
/

--CAP NHAT DATA
UPDATE DBA_QLBV.NHANVIEN
SET OLS_NHANVIEN = CHAR_TO_LABEL('ACCESS_NHANVIEN','QL:NS:CNA')
WHERE MANHANVIEN = 'NV100';

UPDATE DBA_QLBV.NHANVIEN
SET OLS_NHANVIEN = CHAR_TO_LABEL('ACCESS_NHANVIEN','QL:NS:CNB')
WHERE MANHANVIEN = 'NV000';

UPDATE DBA_QLBV.NHANVIEN
SET OLS_NHANVIEN = CHAR_TO_LABEL('ACCESS_NHANVIEN','NV:NS:CNA')
WHERE MANHANVIEN != 'NV100' AND CHINHANH = 'CNA';

UPDATE DBA_QLBV.NHANVIEN
SET OLS_NHANVIEN = CHAR_TO_LABEL('ACCESS_NHANVIEN','NV:CM:CNB')
WHERE MANHANVIEN != 'NV000' AND CHINHANH = 'CNB';

UPDATE DBA_QLBV.NHANVIEN
SET OLS_NHANVIEN = CHAR_TO_LABEL('ACCESS_NHANVIEN','NV:CM:CNA')
WHERE MANHANVIEN != 'NV100' AND CHINHANH = 'CNA' AND MABOPHAN = 'BP007';

COMMIT;

--DAT NHAN CHO USER
BEGIN

    SA_USER_ADMIN.SET_USER_LABELS
    (POLICY_NAME    => 'ACCESS_NHANVIEN',
    USER_NAME       => 'QLNS_CNA',
    MAX_READ_LABEL  => 'NV:NS,CM:CNA');
    
    SA_USER_ADMIN.SET_USER_LABELS
    (POLICY_NAME    => 'ACCESS_NHANVIEN',
    USER_NAME       => 'NVNS_CNA',
    MAX_READ_LABEL  => 'NV:NS,CM:CNA');

    SA_USER_ADMIN.SET_USER_LABELS
    (POLICY_NAME    => 'ACCESS_NHANVIEN',
    USER_NAME       => 'QLCM_CNA',
    MAX_READ_LABEL  => 'QL:CM:CNA');
END;
/
